name: release

on: push

env:
    REGISTRY: ghcr.io

jobs:
    multi-registries:
        name: "Build"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3